# Generated by Django 4.1.3 on 2022-11-10 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='gender_of_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('profile_picture', models.ImageField(upload_to='')),
                ('mobile_number', models.CharField(default='0000000000', max_length=10, validators=[users.models.validate_phone])),
                ('no_of_properties_sold', models.PositiveIntegerField(default=0)),
                ('no_of_properties_bought', models.PositiveIntegerField(default=0)),
                ('is_premium_agent', models.BooleanField(default=False)),
                ('is_premium_client', models.BooleanField(default=True)),
                ('rating', models.FloatField()),
                ('gender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.gender_of_user')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
