# Generated by Django 4.1.3 on 2022-11-10 12:21

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_users_profile_picture_alter_users_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='gender',
            field=models.ForeignKey(null=True, on_delete=users.models.gender_default, to='users.gender_of_user'),
        ),
        migrations.AlterField(
            model_name='users',
            name='rating',
            field=models.FloatField(default=0, null=True),
        ),
    ]
