# Generated by Django 4.1.3 on 2022-11-10 13:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0004_alter_users_gender_alter_users_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='gender',
            field=models.ForeignKey(default=(), null=True, on_delete=users.models.gender_default, to='users.gender_of_user'),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
